hydra:
  job:
    chdir: True
  run:
    dir: ./outputs/

# data configs
data_dir: /home/h5

# training configs
batch_size: 1
epochs: 500
num_training_samples: 400
num_training_time_steps: 300
lr: 0.0001
lr_decay_rate: 0.9999991
num_input_features: 5
num_output_features: 4
num_edge_features: 4

# performance configs
use_apex: True
amp: False
jit: False
num_dataloader_workers: 1
do_concat_trick: False
num_processor_checkpoint_segments: 0
recompute_activation: False

# wandb configs
wandb_mode: disabled
watch_model: False

ckpt_path: "./checkpoints"

# test & visualization configs
num_test_samples: 10
num_test_time_steps: 300
viz_vars: ["u", "v", "p"]
frame_skip: 10
frame_interval: 1